// RSVP-specific constants
export const RSVP = {
  ORP_POSITION: 35,
  SWIPE_MIN_PX: 40,
  COUNTDOWN_TICK_MS: 600,
  STEP_HOLD_DELAY_MS: 350,
  STEP_REPEAT_MS: 110,
  TOAST_DURATION_MS: 1000,
  REWIND_WORDS_ON_RESUME: 3,
  RAMP_STEPS: 5,
  WPM_ADJUST_STEP: 25,
  WPM_MIN: 100,
  WPM_MAX: 800,
  TICK_PX: 18,
  FS_AUTO_HIDE_MS: 2000,
  MAX_CHAPTER_TITLE_LEN: 80,
  FONT_SIZE_MIN: 24,
  FONT_SIZE_MAX: 96,
  FONT_SIZE_STEP: 4,
  LEN_THRESHOLD: 4,
  LEN_SCALE: 250,
};

// RSVP default prefs (used with parameterized PrefsManager)
export const RSVP_DEFAULTS = {
  v: 1,
  theme: 'dark',
  font: 'mono',
  fontSize: 48,
  wpm: 400,
  chunkSize: 1,
  granularity: 'word',
  lengthStrength: 50,
  commaPause: 50,
  periodPause: 120,
  paraPause: 150,
  startPaused: true,
  countdownEnabled: true,
  contextEnabled: true,
  autoPauseEnabled: true,
  trainingEnabled: false,
  trainingIncrement: 10,
  trainingInterval: 500,
  trainingCeiling: 600,
  controlsLevel: 2,
};
