export const TTS_DEFAULTS = {
  v: 1,
  theme: 'dark',
  font: 'serif',
  size: 19,
  lineHeight: 1.62,
  margin: 'normal',
  align: 'justify',
  brightness: 1,
  warmth: 0,
  rate: 1.0,
  pitch: 1.0,
  voiceName: '',
  autoScroll: true,
  highlightMode: 'sentence',
};
